# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['launch_web.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config\\run_config.json', 'config'),
        ('data\\official_fields.json', 'data'),
        ('data\\official_fields.meta.json', 'data'),
        ('data\\official_operators.json', 'data'),
        ('data\\official_operators.meta.json', 'data'),
        ('data\\official_datasets.json', 'data'),
        ('data\\official_datasets.meta.json', 'data'),
        ('data\\official_context_refresh_status.json', 'data'),
        ('brain_alpha_ops\\web\\index.html', 'brain_alpha_ops\\web'),
        ('brain_alpha_ops\\research\\hypotheses', 'brain_alpha_ops\\research\\hypotheses'),
        ('brain_alpha_ops\\research\\prompts', 'brain_alpha_ops\\research\\prompts'),
    ],
    hiddenimports=[
        'brain_alpha_ops',
        'brain_alpha_ops.config',
        'brain_alpha_ops.models',
        'brain_alpha_ops.runner',
        'brain_alpha_ops.cli',
        'yaml',
        'brain_alpha_ops.research',
        'brain_alpha_ops.research.pipeline',
        'brain_alpha_ops.research.generator',
        'brain_alpha_ops.research.validated_generator',
        'brain_alpha_ops.research.scoring',
        'brain_alpha_ops.research.scoring_params',
        'brain_alpha_ops.research.safety',
        'brain_alpha_ops.research.alpha_checks',
        'brain_alpha_ops.research.convergence',
        'brain_alpha_ops.research.auto_calibrator',
        'brain_alpha_ops.research.iterative_optimizer',
        'brain_alpha_ops.research.fusion',
        'brain_alpha_ops.research.repository',
        'brain_alpha_ops.research.experience',
        'brain_alpha_ops.research.diagnostics',
        'brain_alpha_ops.research.dataset_selector',
        'brain_alpha_ops.research.templates',
        'brain_alpha_ops.research.theme_engine',
        'brain_alpha_ops.research.hypothesis_library',
        'brain_alpha_ops.research.hypothesis_driven_generator',
        'brain_alpha_ops.brain_api',
        'brain_alpha_ops.brain_api.base',
        'brain_alpha_ops.brain_api.official',
        'brain_alpha_ops.brain_api.context_defaults',
        'brain_alpha_ops.data',
        'brain_alpha_ops.data.loader',
        'brain_alpha_ops.data.schemas',
        'brain_alpha_ops.data.field_dataset_mapper',
        'brain_alpha_ops.web',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='BrainAlphaOps',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
