"""Constants and path bootstrap for the quality_gate subpackage.

Split from the former ``scripts/quality_gate.py`` monolith (Task A5).
"""

from __future__ import annotations

import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_CONFIG = ROOT / "config" / "run_config.json"
DEFAULT_HTML = ROOT / "brain_alpha_ops" / "web" / "react_app" / "dist" / "index.html"
DEFAULT_SUBPROCESS_TIMEOUT_SECONDS = 300
PYTEST_TIMEOUT_SECONDS = 900
COVERAGE_PYTEST_ARGS = ["--cov=brain_alpha_ops", "--cov-report=term", "--cov-fail-under=80"]
SUBPROCESS_ENV_ALLOWLIST = {
    "CI",
    "COMSPEC",
    "HOME",
    "LANG",
    "LC_ALL",
    "LC_CTYPE",
    "LOGNAME",
    "PATH",
    "PATHEXT",
    "PYTHONHOME",
    "PYTHONIOENCODING",
    "PYTHONNOUSERSITE",
    "PYTHONPATH",
    "PYTHONUTF8",
    "RUNNER_OS",
    "SYSTEMROOT",
    "TEMP",
    "TMP",
    "TMPDIR",
    "USER",
    "VIRTUAL_ENV",
}
COMPILE_TARGETS = [
    "brain_alpha_ops",
    "scripts",
    "tests",
    "build_prod.py",
    "fetch_official_context.py",
    "launch_web.py",
    "validate_data.py",
    "_launch_monitor.py",
    "_status.py",
]
FRONTEND_INLINE_BUILDER = ROOT / "brain_alpha_ops" / "build_inline.py"
STATIC_ANALYSIS_TARGETS = [
    "brain_alpha_ops/build_inline.py",
    "brain_alpha_ops/web/config/web_config.py",
    "brain_alpha_ops/web/misc/web_assistant_snapshots.py",
    "brain_alpha_ops/web/candidates/web_check_availability.py",
    "brain_alpha_ops/web/candidates/web_check_batch_context.py",
    "brain_alpha_ops/web/misc/web_cloud_context_refresh.py",
    "brain_alpha_ops/web/dispatch/web_get_handlers.py",
    "brain_alpha_ops/web/dispatch/web_handler_dispatch.py",
    "brain_alpha_ops/web/dispatch/web_post_handlers.py",
    "brain_alpha_ops/web/business/web_run_job.py",
    "brain_alpha_ops/web/state/web_runtime_state.py",
    "brain_alpha_ops/web/security/web_security.py",
    "brain_alpha_ops/web/misc/web_server_lifecycle.py",
    "brain_alpha_ops/web/misc/web_review_api.py",
    "brain_alpha_ops/web/misc/web_sqlite_indexes.py",
    "brain_alpha_ops/web/submissions/web_submission_batch.py",
    "brain_alpha_ops/web/submissions/web_submission_single.py",
    "brain_alpha_ops/web/misc/web_sync_status_payload.py",
    "brain_alpha_ops/config_models.py",
    "brain_alpha_ops/runtime_constants.py",
    "brain_alpha_ops/secure_credentials.py",
    "brain_alpha_ops/redaction.py",
    "brain_alpha_ops/config/_loader.py",
    "brain_alpha_ops/task_executor.py",
    "brain_alpha_ops/research/anti_overfit.py",
    "brain_alpha_ops/research/batch_backtest_coordinator.py",
    "brain_alpha_ops/research/dataset_selection.py",
    "brain_alpha_ops/research/expression_engine.py",
    "brain_alpha_ops/research/experience_feedback.py",
    "brain_alpha_ops/research/generation_phase.py",
    "brain_alpha_ops/research/knowledge_base.py",
    "brain_alpha_ops/research/llm_review.py",
    "brain_alpha_ops/research/official_workflow.py",
    "brain_alpha_ops/research/research_cycle_orchestrator.py",
    "brain_alpha_ops/research/record_sqlite_index.py",
    "brain_alpha_ops/research/rolling_validation.py",
    "brain_alpha_ops/research/robustness_policy.py",
    "brain_alpha_ops/research/sqlite_index_manifest.py",
    "brain_alpha_ops/research/strategy_plugins.py",
    "brain_alpha_ops/research/strategy_switch.py",
    "brain_alpha_ops/research/production_context.py",
    "brain_alpha_ops/scoring/release_score_gate/__init__.py",
    "brain_alpha_ops/scoring/release_score_gate/_models.py",
    "brain_alpha_ops/scoring/release_score_gate/_checks.py",
    "brain_alpha_ops/scoring/release_score_gate/_decision.py",
    "brain_alpha_ops/scoring/release_score_gate/_helpers.py",
    "brain_alpha_ops/data/official_context_validation.py",
    "scripts/check_dependency_policy.py",
    "scripts/check_brain_contract.py",
    "scripts/check_diagnostic_report.py",
    "scripts/check_diagnosis_gap_coverage.py",
    "scripts/final_release_gate.py",
    "scripts/check_web_console_contract.py",
    "scripts/check_frontend_innerhtml.py",
    "scripts/check_frontend_silent_catches.py",
    "scripts/check_react_build_env.py",
    "scripts/check_module_size.py",
    "scripts/check_optional_tooling.py",
    "scripts/check_official_context.py",
    "scripts/check_python_silent_broad_exceptions.py",
    "scripts/check_frontend_surface_parity.py",
    "scripts/check_review_gap_closure_tracker.py",
    "scripts/check_defect_analysis_report.py",
    "scripts/check_v5_defect_tracking.py",
    "scripts/check_prod_defect_tracking.py",
    "scripts/check_text_encoding.py",
    "scripts/check_tracked_data_inventory.py",
    "scripts/check_candidate_scientific_audit.py",
    "scripts/quality_gate",
    "tests/test_frontend_surface_parity.py",
    "tests/test_quality_gate.py",
    "tests/test_review_gap_closure_tracker.py",
    "tests/test_defect_analysis_report.py",
    "tests/test_v5_defect_tracking.py",
    "tests/test_prod_defect_tracking.py",
    "tests/test_tracked_data_inventory.py",
    "tests/test_candidate_scientific_audit_check.py",
    "tests/test_strategy_plugins.py",
    "tests/test_production_context.py",
    "tests/test_official_context_validation.py",
    "tests/test_web_assistant_snapshots.py",
    "tests/test_web_build_inline.py",
    "tests/test_web_console_contract.py",
    "tests/test_frontend_innerhtml_guard.py",
    "tests/test_frontend_silent_catches_guard.py",
    "tests/test_python_silent_broad_exceptions_guard.py",
    "tests/test_react_build_env_check.py",
    "tests/test_web_check_availability.py",
    "tests/test_web_candidate_check.py",
    "tests/test_web_candidate_scientific_audit.py",
    "tests/test_web_candidate_generation.py",
    "tests/test_web_candidate_optimization.py",
    "tests/test_web_candidate_payloads.py",
    "tests/test_web_candidate_selection.py",
    "tests/test_web_cloud_context_refresh.py",
    "tests/test_web_get_handlers.py",
    "tests/test_web_handler_dispatch.py",
    "tests/test_web_post_handlers.py",
    "tests/test_web_run_job.py",
    "tests/test_web_runtime_state.py",
    "tests/test_web_security.py",
    "tests/test_web_server_lifecycle.py",
    "tests/test_web_review_api.py",
    "tests/test_web_sqlite_indexes.py",
    "tests/test_web_submission_batch.py",
    "tests/test_web_submission_single.py",
    "tests/test_web_submission_safety.py",
    "tests/test_anti_overfit.py",
    "tests/test_batch_backtest_coordinator.py",
    "tests/test_dataset_selection.py",
    "tests/test_expression_engine.py",
    "tests/test_experience_feedback.py",
    "tests/test_generation_phase.py",
    "tests/test_knowledge_base.py",
    "tests/test_llm_review.py",
    "tests/test_official_workflow.py",
    "tests/test_research_cycle_orchestrator.py",
    "tests/test_record_sqlite_index.py",
    "tests/test_rolling_validation.py",
    "tests/test_robustness_policy.py",
    "tests/test_strategy_switch.py",
    "tests/test_task_executor.py",
]
