"""Scientific scoring layer for BRAIN Alpha Ops."""

from brain_alpha_ops.scoring.anti_overfit import (
    ANTI_OVERFIT_SCHEMA_VERSION,
    AntiOverfitResult,
    AntiOverfitService,
    ComplianceGuardrailResult,
    check_duplicate_submission,
    check_expression_similarity,
    check_high_frequency_retry,
    check_parameter_tweak,
    compute_ic_stability,
    compute_placebo_test,
    compute_regime_stress,
    evaluate_candidate,
    estimate_half_life,
    run_compliance_guardrails,
    run_anti_overfit_suite,
)
from brain_alpha_ops.scoring.history import ScoreHistoryDB
from brain_alpha_ops.scoring.local_quality import (
    LocalQualityConfig,
    extract_fields,
    extract_operators,
    local_quality,
    nesting_depth,
)
from brain_alpha_ops.scoring.release_score_gate import (
    GateDecision,
    OfficialSnapshot,
    ScoreAttribution,
    ThresholdPolicy,
    decide_release,
    evaluate_release_score,
)
from brain_alpha_ops.scoring.dsr import (
    ALPHA_SOURCE_DATA,
    ALPHA_SOURCE_HYPOTHESIS,
    DEFAULT_KURTOSIS,
    DEFAULT_SHARPE_STD,
    DEFAULT_SKEWNESS,
    DEFAULT_T,
    DSR_DATA_DRIVEN_MIN,
    DSR_FILTER_THRESHOLD,
    DSR_HYPOTHESIS_DRIVEN_MIN,
    DSR_PASS_THRESHOLD,
    DSRThresholdPolicy,
    USE_DSR_ENV_VAR,
    deflated_sharpe_ratio,
    dsr_gate_decision,
    expected_max_sharpe,
    probabilistic_sharpe_ratio,
    use_dsr_enabled,
)
from brain_alpha_ops.scoring.scoring_context import ScoringContext
from brain_alpha_ops.scoring.schema import (
    GATE_RESULT_SCHEMA,
    SCORECARD_DICT_SCHEMA,
    SCORING_RESULT_SCHEMA,
    validate_gate_result,
    validate_scoring_result,
)

__all__ = [
    "GateDecision",
    "OfficialSnapshot",
    "ScoreAttribution",
    "ThresholdPolicy",
    "ScoreHistoryDB",
    "ANTI_OVERFIT_SCHEMA_VERSION",
    "AntiOverfitResult",
    "AntiOverfitService",
    "ComplianceGuardrailResult",
    "evaluate_candidate",
    "run_anti_overfit_suite",
    "run_compliance_guardrails",
    "check_expression_similarity",
    "check_parameter_tweak",
    "check_duplicate_submission",
    "check_high_frequency_retry",
    "compute_ic_stability",
    "compute_regime_stress",
    "compute_placebo_test",
    "estimate_half_life",
    "decide_release",
    "evaluate_release_score",
    "LocalQualityConfig",
    "extract_fields",
    "extract_operators",
    "local_quality",
    "nesting_depth",
    "SCORING_RESULT_SCHEMA",
    "GATE_RESULT_SCHEMA",
    "SCORECARD_DICT_SCHEMA",
    "validate_scoring_result",
    "validate_gate_result",
    # DSR (Deflated Sharpe Ratio) — Bailey & Lopez de Prado 2014
    "ScoringContext",
    "DSRThresholdPolicy",
    "deflated_sharpe_ratio",
    "probabilistic_sharpe_ratio",
    "expected_max_sharpe",
    "dsr_gate_decision",
    "use_dsr_enabled",
    "DEFAULT_T",
    "DEFAULT_SHARPE_STD",
    "DEFAULT_SKEWNESS",
    "DEFAULT_KURTOSIS",
    "DSR_PASS_THRESHOLD",
    "DSR_FILTER_THRESHOLD",
    "DSR_HYPOTHESIS_DRIVEN_MIN",
    "DSR_DATA_DRIVEN_MIN",
    "ALPHA_SOURCE_HYPOTHESIS",
    "ALPHA_SOURCE_DATA",
    "USE_DSR_ENV_VAR",
]
