"""Protocol defining the expected interface for web request handlers."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class WebHandler(Protocol):
    """Protocol defining the expected interface for web request handlers.

    All handler dispatch functions receive a handler implementing this interface.
    """

    def _send_json(self, payload: dict, status: int = 200, *, extra_headers: list[tuple[str, str]] | None = None) -> None: ...
    def _send_html(self, html: str | bytes, *, extra_headers: list[tuple[str, str]] | None = None) -> None: ...
    def _json(self, payload: dict, status: int = 200) -> None: ...
    def _html(self, html: str | bytes, status: int = 200) -> None: ...
    def _read_json(self) -> dict: ...
    def _has_valid_session(self, query: Any = None) -> bool: ...
    def _validate_replay_request(self) -> dict: ...
    def _session_id_from_cookie(self) -> str: ...
    def _is_allowed_local_request(self) -> bool: ...
    @property
    def headers(self) -> Any: ...
    @property
    def client_address(self) -> tuple[str, int]: ...
