"""Legacy public export mapping for the ``brain_alpha_ops.web`` facade."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any


LEGACY_EXPORT_SPECS = (
    ("RunConfig", "_RunConfig"),
    ("load_run_config", "_load_run_config"),
    ("runtime_project_root", "_runtime_project_root"),
    ("payload_truthy", "_payload_truthy"),
    ("public_config_schema", "_public_config_schema"),
    ("web_html", "_web_html"),
    ("DEFAULT_FIELDS", "_DEFAULT_FIELDS"),
    ("DEFAULT_OPERATORS", "_DEFAULT_OPERATORS"),
    ("tail_text_lines", "_tail_text_lines_service"),
    ("error_payload", "_error_payload"),
    ("ThreadTaskExecutor", "_ThreadTaskExecutor"),
    ("WebJobRegistry", "_WebJobRegistry"),
    ("build_research_observability_snapshot", "_build_research_observability_snapshot"),
    ("ResearchRepository", "_ResearchRepository"),
    ("SubmissionLedger", "_SubmissionLedger"),
    ("api_from_run_config", "_api_from_run_config"),
    ("run_pipeline_from_config", "_run_pipeline_from_config"),
    ("DurableJobStore", "_DurableJobStore"),
    ("run_check_batch_job_service", "_run_check_batch_job_service"),
    ("check_candidate_payload", "_check_candidate_payload"),
    ("candidate_official_metrics", "_candidate_official_metrics"),
    ("is_passed_candidate_for_check", "_is_passed_candidate_for_check"),
    ("official_alpha_id", "_official_alpha_id"),
    ("refresh_cloud_context_for_check_service", "_refresh_cloud_context_for_check_service"),
    ("active_job_payload", "_active_job_payload"),
    ("health_payload", "_health_payload"),
    ("job_status_payload", "_job_status_payload"),
    ("lifecycle_payload", "_lifecycle_payload"),
    ("presets_payload", "_presets_payload"),
    ("profile_payload", "_profile_payload"),
    ("assistant_response_guidance_post_payload", "_assistant_response_guidance_post_payload"),
    ("assistant_response_parse_post_payload", "_assistant_response_parse_post_payload"),
    ("background_job_start_payload", "_background_job_start_payload"),
    ("connection_test_post_payload", "_connection_test_post_payload"),
    ("save_assistant_guidance_post_payload", "_save_assistant_guidance_post_payload"),
    ("session_end_payload", "_session_end_payload"),
    ("stop_job_payload", "_stop_job_payload"),
    ("RequestRateLimiter", "_RequestRateLimiter"),
    ("WebDispatchActionContext", "_WebDispatchActionContext"),
    ("WebDispatchAssistantContext", "_WebDispatchAssistantContext"),
    ("WebDispatchConfigContext", "_WebDispatchConfigContext"),
    ("WebDispatchCoreContext", "_WebDispatchCoreContext"),
    ("WebDispatchJobContext", "_WebDispatchJobContext"),
    ("WebDispatchResearchContext", "_WebDispatchResearchContext"),
    ("WebDispatchSessionContext", "_WebDispatchSessionContext"),
    ("WebHandlerDispatchContext", "_WebHandlerDispatchContext"),
    ("dispatch_get", "_dispatch_get"),
    ("dispatch_post", "_dispatch_post"),
    ("create_handler_class", "_create_handler_class"),
    ("route_for", "_route_for"),
    ("progress_update", "_progress_update"),
    ("run_simple_async_job_service", "_run_simple_async_job_service"),
    ("run_guided_job_service", "_run_guided_job_service"),
    ("run_job_service", "_run_job_service"),
    ("web_session", "_web_session"),
    ("WebSnapshotFacade", "_WebSnapshotFacade"),
    ("WebSnapshotRuntime", "_WebSnapshotRuntime"),
    ("DEFAULT_SESSION_TTL_SECONDS", "_DEFAULT_SESSION_TTL_SECONDS"),
    ("LOOPBACK_BIND_HOSTS", "_LOOPBACK_BIND_HOSTS"),
    ("SESSION_COOKIE_NAME", "_SESSION_COOKIE_NAME"),
    ("submit_batch_payload", "_submit_batch_payload"),
    ("submit_candidate_payload", "_submit_candidate_payload"),
    ("run_sync_job_service", "_run_sync_job_service"),
    ("sync_cloud_alphas_payload", "_sync_cloud_alphas_payload"),
    ("CloudDefaults", "_CloudDefaults"),
    ("WebDefaults", "_WebDefaults"),
    ("SnapshotDefaults", "_SnapshotDefaults"),
)


def build_legacy_imported_exports(namespace: Mapping[str, Any]) -> dict[str, Any]:
    return {public_name: namespace[private_name] for public_name, private_name in LEGACY_EXPORT_SPECS}
